# action.yml
name: 'Check URLs'
description: 'Check URLs from a JSON file'
inputs:
  filename:
    description: 'Filename of the JSON file'
    required: false
    default: './urls.json'
branding:
  icon: check-square
  color: gray-dark
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ./json/single-bad.json
