# action.yml
name: 'Check URLs'
description: 'Check URLs from a JSON file'
branding:
  icon: check-square
  color: gray-dark
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ./json/single-bad.json
